# config.yaml
num_workers: 8
log_dir: 'logs'
paper:
  dir: '../figs/random_rotations'

model:
  patch_size: 4
  "img_w": 32
  "rgb_c": 1
  "n_qubits": 4
  "n_layers": 1
  "qconv2d_layers": 1
  "batch_size": 128
  "num_epochs": 50
  "learning_rate": 0.001
  "singlExp_val_global": False
  "d_stride": 3
  "test_images": 1
  "actual_pct": 0.2
  "dim_in": 0
  "latent_v": 64
  "sample_shots": 20
  "samples": 2000
training:
  num_epochs: 60
  q_lr: 0.01
  c_lr: 0.0001
  q_dropout: 0.0
  batch_size: 18
hydra:
  run:
    dir: 'logs'
#version_base=null
